CREATE TABLE requests (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    u_id INT NOT NULL,
    hash VARCHAR(256) UNIQUE NOT NULL,
    data JSON DEFAULT NULL
);

CREATE TABLE uids (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    service_id INT NOT NULL,
    service_family ENUM('email_service') NOT NULL,
    data JSON DEFAULT NULL
);

CREATE TABLE changes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    u_id INT NOT NULL,
    field_name VARCHAR(64) NOT NULL,
    old_value TEXT,
    new_value TEXT
);

CREATE TABLE email_service (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    internal_id VARCHAR(256) UNIQUE NOT NULL,
    data JSON DEFAULT NULL
);

CREATE TABLE phone_service (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    internal_id VARCHAR(256) UNIQUE NOT NULL,
    data JSON DEFAULT NULL
);

-- SELECT REPLACE(SUBSTRING(COLUMN_TYPE,6,(LENGTH(COLUMN_TYPE)-6)),"'","")
-- FROM information_schema.COLUMNS
-- WHERE TABLE_SCHEMA='__TABLE_SCHEMA__' 
-- AND TABLE_NAME='__TABLE_NAME__'
-- AND COLUMN_NAME='__COLUMN_NAME__'

CREATE OR REPLACE TRIGGER 
  create_service_table_trigger
  AFTER INSERT ON SCHEMA
BEGIN
  SELECT SYS.DICTIONARY_OBJ_TYPE
END;

ALTER TABLE uids MODIFY COLUMN service_family ENUM(
    (SELECT GROUP_CONCAT(QUOTE(TABLE_NAME)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%_service')
);